-- CreateMeasurementProfileTable
-- This migration:
-- 1. Renames the old Measurement table to MeasurementProfile
-- 2. Removes the @unique constraint on userId
-- 3. Adds profileName (default 'Default') and isDefault fields
-- 4. Adds a compound unique on [userId, profileName]

-- Step 1: Create new table with the updated schema
CREATE TABLE "MeasurementProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "profileName" TEXT NOT NULL DEFAULT 'Default',
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "length1" TEXT NOT NULL DEFAULT '',
    "length2" TEXT NOT NULL DEFAULT '',
    "shoulder1" TEXT NOT NULL DEFAULT '',
    "shoulder2" TEXT NOT NULL DEFAULT '',
    "chest1" TEXT NOT NULL DEFAULT '',
    "chest2" TEXT NOT NULL DEFAULT '',
    "waist1" TEXT NOT NULL DEFAULT '',
    "waist2" TEXT NOT NULL DEFAULT '',
    "gherra1" TEXT NOT NULL DEFAULT '',
    "gherra2" TEXT NOT NULL DEFAULT '',
    "neck1" TEXT NOT NULL DEFAULT '',
    "neck2" TEXT NOT NULL DEFAULT '',
    "sleeves1" TEXT NOT NULL DEFAULT '',
    "sleeves2" TEXT NOT NULL DEFAULT '',
    "golai1" TEXT NOT NULL DEFAULT '',
    "golai2" TEXT NOT NULL DEFAULT '',
    "armcuff1" TEXT NOT NULL DEFAULT '',
    "armcuff2" TEXT NOT NULL DEFAULT '',
    "armplate1" TEXT NOT NULL DEFAULT '',
    "armplate2" TEXT NOT NULL DEFAULT '',
    "golbazoo1" TEXT NOT NULL DEFAULT '',
    "golbazoo2" TEXT NOT NULL DEFAULT '',
    "armpatti1" TEXT NOT NULL DEFAULT '',
    "armpatti2" TEXT NOT NULL DEFAULT '',
    "collarnok1" TEXT NOT NULL DEFAULT '',
    "collarnok2" TEXT NOT NULL DEFAULT '',
    "bane1" TEXT NOT NULL DEFAULT '',
    "bane2" TEXT NOT NULL DEFAULT '',
    "doubleCb" TEXT NOT NULL DEFAULT '0',
    "singleCb" TEXT NOT NULL DEFAULT '0',
    "golCb" TEXT NOT NULL DEFAULT '0',
    "chorasCb" TEXT NOT NULL DEFAULT '0',
    "baneCb" TEXT NOT NULL DEFAULT '0',
    "collarCb" TEXT NOT NULL DEFAULT '0',
    "roundneck" TEXT NOT NULL DEFAULT '0',
    "shalwar1" TEXT NOT NULL DEFAULT '',
    "shalwar2" TEXT NOT NULL DEFAULT '',
    "shalwarGherra1" TEXT NOT NULL DEFAULT '',
    "shalwarGherra2" TEXT NOT NULL DEFAULT '',
    "shalwarAssan1" TEXT NOT NULL DEFAULT '',
    "shalwarAssan2" TEXT NOT NULL DEFAULT '',
    "shalwarPancha1" TEXT NOT NULL DEFAULT '',
    "shalwarPancha2" TEXT NOT NULL DEFAULT '',
    "frontPocket" TEXT NOT NULL DEFAULT '',
    "sidePocket" TEXT NOT NULL DEFAULT '',
    "shalwarPocket" TEXT NOT NULL DEFAULT '',
    "trouserdata1" TEXT NOT NULL DEFAULT '',
    "trouserdata2" TEXT NOT NULL DEFAULT '',
    "trouserdata3" TEXT NOT NULL DEFAULT '',
    "trouserdata4" TEXT NOT NULL DEFAULT '',
    "trouserdata5" TEXT NOT NULL DEFAULT '',
    "trouserdata6" TEXT NOT NULL DEFAULT '',
    "trouserdata7" TEXT NOT NULL DEFAULT '',
    "trouserdata8" TEXT NOT NULL DEFAULT '',
    "trouserdata9" TEXT NOT NULL DEFAULT '',
    "trouserdata10" TEXT NOT NULL DEFAULT '',
    "trouserdata11" TEXT NOT NULL DEFAULT '',
    "trouserdata12" TEXT NOT NULL DEFAULT '',
    "trouserdata13" TEXT NOT NULL DEFAULT '',
    "trouserdata14" TEXT NOT NULL DEFAULT '0',
    "ladGolai1" TEXT NOT NULL DEFAULT '',
    "ladGolai2" TEXT NOT NULL DEFAULT '',
    "ladMori1" TEXT NOT NULL DEFAULT '',
    "ladMori2" TEXT NOT NULL DEFAULT '',
    "ladBellbazoo1" TEXT NOT NULL DEFAULT '',
    "ladBellbazoo2" TEXT NOT NULL DEFAULT '',
    "ladChaak1" TEXT NOT NULL DEFAULT '',
    "ladChaak2" TEXT NOT NULL DEFAULT '',
    "ladHip1" TEXT NOT NULL DEFAULT '',
    "ladHip2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwar1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwar2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarPancha1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarPancha2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarGherra1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarGherra2" TEXT NOT NULL DEFAULT '',
    "ladLasticSimpleShalwar" TEXT NOT NULL DEFAULT '',
    "ladShalwarBelt1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBelt2" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltPancha1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltPancha2" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltGherra1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltGherra2" TEXT NOT NULL DEFAULT '',
    "ladLasticShalwarBelt" TEXT NOT NULL DEFAULT '',
    "ladTrouserdata15" TEXT NOT NULL DEFAULT '',
    "ladTrouserdata16" TEXT NOT NULL DEFAULT '0',
    "gender" TEXT NOT NULL DEFAULT 'Male',
    "deliveryDate" TIMESTAMP(3),
    "notes" TEXT NOT NULL DEFAULT '',
    "garmentType" TEXT NOT NULL DEFAULT 'male_shalwar_kameez',
    "deletedAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'pending',
    "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "MeasurementProfile_pkey" PRIMARY KEY ("id")
);

-- Step 2: Migrate existing data from Measurement to MeasurementProfile
-- Each existing row becomes a profile named "Default" with isDefault=true
INSERT INTO "MeasurementProfile" (
    "id", "userId", "profileName", "isDefault",
    "length1", "length2", "shoulder1", "shoulder2",
    "chest1", "chest2", "waist1", "waist2",
    "gherra1", "gherra2", "neck1", "neck2",
    "sleeves1", "sleeves2", "golai1", "golai2",
    "armcuff1", "armcuff2", "armplate1", "armplate2",
    "golbazoo1", "golbazoo2", "armpatti1", "armpatti2",
    "collarnok1", "collarnok2", "bane1", "bane2",
    "doubleCb", "singleCb", "golCb", "chorasCb",
    "baneCb", "collarCb", "roundneck",
    "shalwar1", "shalwar2", "shalwarGherra1", "shalwarGherra2",
    "shalwarAssan1", "shalwarAssan2", "shalwarPancha1", "shalwarPancha2",
    "frontPocket", "sidePocket", "shalwarPocket",
    "trouserdata1", "trouserdata2", "trouserdata3", "trouserdata4",
    "trouserdata5", "trouserdata6", "trouserdata7", "trouserdata8",
    "trouserdata9", "trouserdata10", "trouserdata11", "trouserdata12",
    "trouserdata13", "trouserdata14",
    "ladGolai1", "ladGolai2", "ladMori1", "ladMori2",
    "ladBellbazoo1", "ladBellbazoo2", "ladChaak1", "ladChaak2",
    "ladHip1", "ladHip2",
    "ladSimpleShalwar1", "ladSimpleShalwar2",
    "ladSimpleShalwarPancha1", "ladSimpleShalwarPancha2",
    "ladSimpleShalwarGherra1", "ladSimpleShalwarGherra2",
    "ladLasticSimpleShalwar",
    "ladShalwarBelt1", "ladShalwarBelt2",
    "ladShalwarBeltPancha1", "ladShalwarBeltPancha2",
    "ladShalwarBeltGherra1", "ladShalwarBeltGherra2",
    "ladLasticShalwarBelt",
    "ladTrouserdata15", "ladTrouserdata16",
    "gender", "deliveryDate", "notes", "garmentType",
    "deletedAt", "status", "requestedAt", "updatedAt"
)
SELECT
    "id", "userId", 'Default', true,
    "length1", "length2", "shoulder1", "shoulder2",
    "chest1", "chest2", "waist1", "waist2",
    "gherra1", "gherra2", "neck1", "neck2",
    "sleeves1", "sleeves2", "golai1", "golai2",
    "armcuff1", "armcuff2", "armplate1", "armplate2",
    "golbazoo1", "golbazoo2", "armpatti1", "armpatti2",
    "collarnok1", "collarnok2", "bane1", "bane2",
    "doubleCb", "singleCb", "golCb", "chorasCb",
    "baneCb", "collarCb", "roundneck",
    "shalwar1", "shalwar2", "shalwarGherra1", "shalwarGherra2",
    "shalwarAssan1", "shalwarAssan2", "shalwarPancha1", "shalwarPancha2",
    "frontPocket", "sidePocket", "shalwarPocket",
    "trouserdata1", "trouserdata2", "trouserdata3", "trouserdata4",
    "trouserdata5", "trouserdata6", "trouserdata7", "trouserdata8",
    "trouserdata9", "trouserdata10", "trouserdata11", "trouserdata12",
    "trouserdata13", "trouserdata14",
    "ladGolai1", "ladGolai2", "ladMori1", "ladMori2",
    "ladBellbazoo1", "ladBellbazoo2", "ladChaak1", "ladChaak2",
    "ladHip1", "ladHip2",
    "ladSimpleShalwar1", "ladSimpleShalwar2",
    "ladSimpleShalwarPancha1", "ladSimpleShalwarPancha2",
    "ladSimpleShalwarGherra1", "ladSimpleShalwarGherra2",
    "ladLasticSimpleShalwar",
    "ladShalwarBelt1", "ladShalwarBelt2",
    "ladShalwarBeltPancha1", "ladShalwarBeltPancha2",
    "ladShalwarBeltGherra1", "ladShalwarBeltGherra2",
    "ladLasticShalwarBelt",
    "ladTrouserdata15", "ladTrouserdata16",
    "gender", "deliveryDate", "notes", "garmentType",
    "deletedAt", "status", "requestedAt", "updatedAt"
FROM "Measurement";

-- Step 3: Drop the old table
DROP TABLE "Measurement";

-- Step 4: Create indexes and constraints
CREATE UNIQUE INDEX "MeasurementProfile_userId_profileName_key" ON "MeasurementProfile"("userId", "profileName");
CREATE INDEX "MeasurementProfile_userId_idx" ON "MeasurementProfile"("userId");
CREATE INDEX "MeasurementProfile_status_idx" ON "MeasurementProfile"("status");
CREATE INDEX "MeasurementProfile_deletedAt_idx" ON "MeasurementProfile"("deletedAt");

-- Step 5: Add foreign key
ALTER TABLE "MeasurementProfile" ADD CONSTRAINT "MeasurementProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;