-- Fix MeasurementProfile table — recreate it to match current Prisma schema
-- The table was missing from the database due to a previous migration gap.

CREATE TABLE "MeasurementProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "profileName" TEXT NOT NULL DEFAULT 'Default',
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "length1" TEXT NOT NULL DEFAULT '',
    "length2" TEXT NOT NULL DEFAULT '',
    "shoulder1" TEXT NOT NULL DEFAULT '',
    "shoulder2" TEXT NOT NULL DEFAULT '',
    "chest1" TEXT NOT NULL DEFAULT '',
    "chest2" TEXT NOT NULL DEFAULT '',
    "waist1" TEXT NOT NULL DEFAULT '',
    "waist2" TEXT NOT NULL DEFAULT '',
    "gherra1" TEXT NOT NULL DEFAULT '',
    "gherra2" TEXT NOT NULL DEFAULT '',
    "neck1" TEXT NOT NULL DEFAULT '',
    "neck2" TEXT NOT NULL DEFAULT '',
    "sleeves1" TEXT NOT NULL DEFAULT '',
    "sleeves2" TEXT NOT NULL DEFAULT '',
    "golai1" TEXT NOT NULL DEFAULT '',
    "golai2" TEXT NOT NULL DEFAULT '',
    "armcuff1" TEXT NOT NULL DEFAULT '',
    "armcuff2" TEXT NOT NULL DEFAULT '',
    "armplate1" TEXT NOT NULL DEFAULT '',
    "armplate2" TEXT NOT NULL DEFAULT '',
    "golbazoo1" TEXT NOT NULL DEFAULT '',
    "golbazoo2" TEXT NOT NULL DEFAULT '',
    "armpatti1" TEXT NOT NULL DEFAULT '',
    "armpatti2" TEXT NOT NULL DEFAULT '',
    "collarnok1" TEXT NOT NULL DEFAULT '',
    "collarnok2" TEXT NOT NULL DEFAULT '',
    "bane1" TEXT NOT NULL DEFAULT '',
    "bane2" TEXT NOT NULL DEFAULT '',
    "doubleCb" TEXT NOT NULL DEFAULT '0',
    "singleCb" TEXT NOT NULL DEFAULT '0',
    "golCb" TEXT NOT NULL DEFAULT '0',
    "chorasCb" TEXT NOT NULL DEFAULT '0',
    "baneCb" TEXT NOT NULL DEFAULT '0',
    "collarCb" TEXT NOT NULL DEFAULT '0',
    "roundneck" TEXT NOT NULL DEFAULT '0',
    "straightCb" TEXT NOT NULL DEFAULT '0',
    "downCb" TEXT NOT NULL DEFAULT '0',
    "shalwar1" TEXT NOT NULL DEFAULT '',
    "shalwar2" TEXT NOT NULL DEFAULT '',
    "shalwarGherra1" TEXT NOT NULL DEFAULT '',
    "shalwarGherra2" TEXT NOT NULL DEFAULT '',
    "shalwarAssan1" TEXT NOT NULL DEFAULT '',
    "shalwarAssan2" TEXT NOT NULL DEFAULT '',
    "shalwarPancha1" TEXT NOT NULL DEFAULT '',
    "shalwarPancha2" TEXT NOT NULL DEFAULT '',
    "frontPocket" TEXT NOT NULL DEFAULT '',
    "sidePocket" TEXT NOT NULL DEFAULT '',
    "shalwarPocket" TEXT NOT NULL DEFAULT '',
    "zipCb" TEXT NOT NULL DEFAULT '0',
    "trouserdata1" TEXT NOT NULL DEFAULT '',
    "trouserdata2" TEXT NOT NULL DEFAULT '',
    "trouserdata3" TEXT NOT NULL DEFAULT '',
    "trouserdata4" TEXT NOT NULL DEFAULT '',
    "trouserdata5" TEXT NOT NULL DEFAULT '',
    "trouserdata6" TEXT NOT NULL DEFAULT '',
    "trouserdata7" TEXT NOT NULL DEFAULT '',
    "trouserdata8" TEXT NOT NULL DEFAULT '',
    "trouserdata9" TEXT NOT NULL DEFAULT '',
    "trouserdata10" TEXT NOT NULL DEFAULT '',
    "trouserdata11" TEXT NOT NULL DEFAULT '',
    "trouserdata12" TEXT NOT NULL DEFAULT '',
    "trouserdata13" TEXT NOT NULL DEFAULT '',
    "trouserdata14" TEXT NOT NULL DEFAULT '0',
    "ladGolai1" TEXT NOT NULL DEFAULT '',
    "ladGolai2" TEXT NOT NULL DEFAULT '',
    "ladMori1" TEXT NOT NULL DEFAULT '',
    "ladMori2" TEXT NOT NULL DEFAULT '',
    "ladBellbazoo1" TEXT NOT NULL DEFAULT '',
    "ladBellbazoo2" TEXT NOT NULL DEFAULT '',
    "ladChaak1" TEXT NOT NULL DEFAULT '',
    "ladChaak2" TEXT NOT NULL DEFAULT '',
    "ladHip1" TEXT NOT NULL DEFAULT '',
    "ladHip2" TEXT NOT NULL DEFAULT '',
    "hip1" TEXT NOT NULL DEFAULT '',
    "hip2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwar1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwar2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarPancha1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarPancha2" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarGherra1" TEXT NOT NULL DEFAULT '',
    "ladSimpleShalwarGherra2" TEXT NOT NULL DEFAULT '',
    "ladLasticSimpleShalwar" TEXT NOT NULL DEFAULT '',
    "ladShalwarBelt1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBelt2" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltPancha1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltPancha2" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltGherra1" TEXT NOT NULL DEFAULT '',
    "ladShalwarBeltGherra2" TEXT NOT NULL DEFAULT '',
    "ladLasticShalwarBelt" TEXT NOT NULL DEFAULT '',
    "ladTrouserdata15" TEXT NOT NULL DEFAULT '',
    "ladTrouserdata16" TEXT NOT NULL DEFAULT '0',
    "ladTrouserElastic1" TEXT NOT NULL DEFAULT '',
    "gender" TEXT NOT NULL DEFAULT 'Male',
    "deliveryDate" TIMESTAMP(3),
    "notes" TEXT NOT NULL DEFAULT '',
    "garmentType" TEXT NOT NULL DEFAULT 'male_shalwar_kameez',
    "source" "MeasurementSource" NOT NULL DEFAULT 'profile',
    "status" "MeasurementProfileStatus" NOT NULL DEFAULT 'pending',
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "MeasurementProfile_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "MeasurementProfile_userId_deletedAt_profileName_idx" ON "MeasurementProfile"("userId", "deletedAt", "profileName");
CREATE INDEX "MeasurementProfile_userId_idx" ON "MeasurementProfile"("userId");
CREATE INDEX "MeasurementProfile_source_idx" ON "MeasurementProfile"("source");
CREATE INDEX "MeasurementProfile_deletedAt_idx" ON "MeasurementProfile"("deletedAt");
CREATE INDEX "MeasurementProfile_userId_deletedAt_idx" ON "MeasurementProfile"("userId", "deletedAt");

ALTER TABLE "MeasurementProfile" ADD CONSTRAINT "MeasurementProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;